# Generated by Django 6.0 on 2026-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joplinupload',
            name='new_notes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joplinupload',
            name='updated_notes_count',
            field=models.IntegerField(default=0),
        ),
    ]
