# Generated by Django 6.0 on 2026-01-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_joplinupload_new_notes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemetadata',
            name='chunk_overlap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notemetadata',
            name='chunk_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
